version: '3.8'
services:
  db-inventory:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: alucard
      POSTGRES_PASSWORD: auth123
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  db-products:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: alucard
      POSTGRES_PASSWORD: auth123
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  db-orders:
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: alucard
      MYSQL_PASSWORD: auth123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306